# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NZkwqqgQpb0vz51efdmeAddPhoFOsYA0
"""

import os
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

student_files = [doc for doc in os.listdir() if doc.endswith('.txt')]
student_files

student_notes = [open(_file,encoding='utf-8').read() for _file in student_files]
student_notes

def vectorize(text):
  return TfidfVectorizer().fit_transform(text).toarray()

def similarity(doc1, doc2):
  return cosine_similarity([doc1, doc2])

vectors = vectorize(student_notes)

vectors

s_vectors = list(zip(student_files,vectors))

s_vectors

plagiarism_result = set()

def check_plagiarism():
  global s_vectors
  for student_a , text_vector_a in s_vectors:
    new_vectors = s_vectors.copy()
    current_index = new_vectors.index((student_a , text_vector_a))
    print(current_index)
    for student_b , text_vector_b in new_vectors:
      sim_score = similarity(text_vector_a , text_vector_b)[0][1]
      student_pair = sorted((student_a , student_b))
      print(similarity(text_vector_a , text_vector_b))
      print(student_pair)
      score = (student_pair[0],student_pair[1],sim_score)
      plagiarism_result.add(score)
  return plagiarism_result

for data in check_plagiarism():
  print(data)

